# To download this file to ubuntu, press raw format,then in ubuntu type curl -LO https://raw.git...(url to this file)
# To execute this docker-compose yml file use `docker-compose -f <file_name> up`
# Add the `-d` flag at the end for detached execution
# to scale nodes: either set NODE_MAX_INSTANCES and NODE_MAX_SESSION in a node's environment, or use Docker scale command (see below)
# full command would be: docker-compose -f "path\dockerComposeSeleniumGrid.yml" up -d --scale chrome=2 --scale firefox=2

# to see the console:
# http://{url}:4444/grid/console

version: "3"
services:
  selenium-hub:
    image: selenium/hub:3.141.59-selenium
    container_name: selenium-hub
    ports:
      - "4444:4444"
  chrome:
    image: selenium/node-chrome-debug
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    ports:
      - 5900
  firefox:
    image: selenium/node-firefox-debug
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    ports:
      - 5900
